#!/bin/sh
### BEGIN INIT INFO
# Provides:          resizebtrfs_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting resizebtrfs_once"
    btrfs filesystem resize max / &&
    update-rc.d resizebtrfs_once remove &&
    rm /etc/init.d/resizebtrfs_once &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
