#!/usr/sbin/nft -f

define wan = {wan0}

table inet router_filter 
delete table inet router_filter 
table inet router_filter {
	chain prerouting {
		type filter hook prerouting priority -101; policy accept;
		iifname $wan jump prerouting_from_wan
	}

	chain prerouting_from_wan {
		# Drop invalid connections
		ct state invalid counter drop

		# Don't route to private ranges
		ip daddr {10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16} counter log prefix "Private daddr from WAN " flags all drop

		# Rate limit ICMP ping
		ip protocol icmp icmp type echo-request limit rate over 100/second counter drop
		ip6 nexthdr icmpv6 icmpv6 type echo-request limit rate over 100/second counter drop
	}

	chain input {
		type filter hook input priority 0; policy accept;
		iifname $wan jump input_from_wan
		iifname eth0.guest jump input_from_guest
	}

	chain input_from_guest {
		# Allow established/related connections
		ct state { established, related } accept

		# Allow ICMP
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# Expose DNS server
		tcp dport 53 accept
		udp dport 53 accept

		# Expose DHCPv4 server
		udp dport bootps udp sport bootpc counter accept

		# Reject everything else
		#log prefix "Reject input from Guest " flags all
		counter reject with icmpx type admin-prohibited
	}

	chain input_from_wan {
		# Allow established/related connections
		ct state { established, related } accept

		# Allow ICMP
		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept
		icmpv6 type { nd-neighbor-solicit, nd-router-advert, nd-neighbor-advert } counter accept

		# DHCPv4 Client
		udp sport bootps udp dport bootpc counter accept

		# DHCPv6 Client
		udp sport dhcpv6-server udp dport dhcpv6-client counter accept

		# Open local ports
		tcp dport 2222 counter accept # sshd
		tcp dport {80, 443} accept # webserver
	
		# Reject everything else
		counter log prefix "Dropped from WAN" reject with icmpx type port-unreachable
	}

	chain forward {
		type filter hook forward priority 0; policy accept;

		# WAN ingress & egress
		oifname $wan counter accept;
		iifname $wan jump forward_from_wan
	
		# Firewall IOT LAN segment
		iifname eth0.iot jump forward_iot_to_lan

		# Isolate guest vlan from other LAN segments
		iifname eth0.guest oifname != $wan counter drop
		oifname eth0.guest iifname != $wan counter drop
	}

	chain forward_from_wan {
		# Allow established/related connections
		ct state { established, related } accept

		# Allow port forwards
		ip daddr 192.168.0.0/16 ct status dnat counter accept

		# Allow ICMP
		ip protocol icmp counter accept
		ip6 nexthdr icmpv6 counter accept

		# Allow incoming connections to select ipv6 hosts
		# TODO

		# Reject everything else
		log prefix "Reject forward from WAN " flags all
		counter reject with icmpx type admin-prohibited
	}

	chain forward_iot_to_lan {
		# Allow established/related connections
		ct state { established, related } accept

		# Allow ICMP
		ip protocol icmp counter accept
		ip6 nexthdr icmpv6 counter accept

		# Reject everything else
		counter reject with icmpx type admin-prohibited
	}


}

table ip router_nat
delete table ip router_nat
table ip router_nat {
	chain prerouting {
		type nat hook prerouting priority -100; policy accept;

		# Port Forwarding
		# tcp dport { ssh, http } dnat to destination_ip
		tcp dport 2223 dnat to 192.168.1.5:2222
	}

	chain postrouting {
		type nat hook postrouting priority 100; policy accept;
		#oifname wan1 ip saddr 192.168.1.37 counter snat to 130.44.149.94
		oifname $wan ip saddr 192.168.0.0/16 counter masquerade
	}

}

