#!/bin/bash -e
# Copy the new initramfs to a fixed location (eg. initrd.img-5.4.51-v8+ -> initrd8.img)
version=$1
src=$2

# Extract "", "7", "7l", or "8" from the end of version
arch=$(echo $version | sed '/^[0-9]\+\.[0-9]\+\.[0-9]\+-v\([78]\?l\?\)+\?$/!d;s//\1/')

dst="$(dirname $src)/initrd$arch.img"

echo "cp -a $src $dst"
cp -a $src $dst
